### ISSUE TITLE
Update `Acquire.validate()` to return a `boolean` instead of crashing out

### ISSUE THREAD

**Issue by dluman** [term-world/term-util#28]
To accommodate changes to the `marketplace`, the `validate` method of `Inventory`'s `Acquire` needs to return a boolean and then act on _that_.

## Tasks which seem relevant:

- [ ] Move validation to `Validator` object in separate file
- [ ] Reintegrate the `self.` operations from the `Acquire.validate` to the `__init__` constructor in `Acquire`
- [ ] Create a `bool` return for new `Validator`
- [ ] Integrate in to `marketplace` `listing` file

**Comment by dluman** [comment]
Question for those assembled: should _items validate themselves_ instead? This means moving the validation to the various `Spec`s instead. Seems to make more sense than validating them at the acquisition level.
